// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int numOfTests = Integer.parseInt(args[0]); // Number of random numbers to generate.

		double randomNum; // Variable to hold each generated random number.

		int countBelowHalf = 0; 
		int countAboveHalf = 0; 

		for (int i = 0; i < numOfTests; i++) { // Loop to generate random numbers according to user input.

			randomNum = Math.random();

			if (randomNum <= 0.5) {
				countBelowHalf++;
			} else {
				countAboveHalf++;
			}
		}

		System.out.println("> 0.5: " + countAboveHalf + " times");
		System.out.println("<= 0.5: " + countBelowHalf + " times");

		double ratio;

		if(countAboveHalf > countBelowHalf) { // To get a ratio always <= 1 and avoid division by zero.

			ratio = countBelowHalf / (double) countAboveHalf; 
		} else {

			ratio = countAboveHalf / (double) countBelowHalf;
		}

		if (ratio != 0) {  // To avoid printing ratio that is 0.
			
			System.out.println("Ratio: " + ratio);
		}
	}
}
